// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as WidgetsSchema } from './widgets/WidgetsSchema';

type Database = WidgetsSchema;

export default Database;
