// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as WidgetTable } from './Widget';

export default interface WidgetsSchema {
  widget: WidgetTable;
}
